### ISSUE TITLE
La version stable sur jeedom ne fonctionne pas

### ISSUE THREAD

**Issue by vegeta0911** [Ynats-Dev/jeedom-plugin-scan.ip#10]
Laquelle branch je dois agir pour la version stable de jeedom sur les corrections pour le passage en Debian 12.
Pour info le système actuelle de jeedom fonctionne très bien avec les correctifs en bêta.

**Comment by Ynats-Dev** [comment]
Pour être prise en compte sur jeedom market il faut pousser sur la branche stable et non master.

**Comment by Ynats-Dev** [comment]
Je pousse tout ça ce soir ou demain 😉

**Comment by Ynats-Dev** [comment]
Un très grand merci !

**Comment by vegeta0911** [comment]
De rien 😉 
il faut que je vois ça pour intégrer les vlans.
En tous cas je trouve ton code très bien fait, c’est rare de voir ça .

**Comment by Ynats-Dev** [comment]
Merci pour ce retour.
Je vais pousser la branche beta sur stable du coup. Car j'ai aussi apporté des modifs (Release note et version).

**Comment by vegeta0911** [comment]
Ok pas de souci.
C’est bon la version stable est opérationnel merci.
