### ISSUE TITLE
Après validation des pull request 

### ISSUE THREAD

**Issue by vegeta0911** [Ynats-Dev/jeedom-plugin-scan.ip#4]
je ne vois pas les modifications validé sur le market en bêta sur jeedom

**Comment by Ynats-Dev** [comment]
Hello, désolé j'ai fait ça sur mon téléphone. Je viens de valider.  Un grand merci pour le fixe :)

**Comment by vegeta0911** [comment]
de rien :).
je te reconcterai prochainement pour le mettre en stable, j'attends le retour des utilisateurs.

**Comment by vegeta0911** [comment]
De rien c'est avec plaisir :)
