### ISSUE TITLE
ajouter scan sur les vlans

### ISSUE THREAD

**Issue by vegeta0911** [Ynats-Dev/jeedom-plugin-scan.ip#9]
j'ai une idée d'amélioration si on pouvez rajouter les vlans dans ton plugin.
je sais que l'option existe sur arp-scan.

car moi j'utilise les vlan et du coup il scan que la ou est connecter mon jeedom.

tu crois que c'est possible de le faire ?

**Comment by Ynats-Dev** [comment]
Hello, je suis beaucoup moins sur le plugin car depuis son lancement j'ai eu deux enfants et j'ai aussi d'autres projets à coté. Mais si tu es chaud pour faire évoluer le plugin pas de soucis bien au contraire. Je pensais aussi faire des traductions.

**Comment by vegeta0911** [comment]
Félicitations jeune papa 😉.
Je vais vois ça si je peu le faire .
